/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125DashboardRouteImport } from './routes/{-$locale}/dashboard'
import { Route as Char123LocaleChar125SignInRouteImport } from './routes/{-$locale}/sign-in'
import { Route as Char123LocaleChar125SignUpRouteImport } from './routes/{-$locale}/sign-up'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125DashboardRoute =
  Char123LocaleChar125DashboardRouteImport.update({
    id: '/{-$locale}/dashboard',
    path: '/{-$locale}/dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SignInRoute =
  Char123LocaleChar125SignInRouteImport.update({
    id: '/{-$locale}/sign-in',
    path: '/{-$locale}/sign-in',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125SignUpRoute =
  Char123LocaleChar125SignUpRouteImport.update({
    id: '/{-$locale}/sign-up',
    path: '/{-$locale}/sign-up',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/sign-in': typeof Char123LocaleChar125SignInRoute
  '/{-$locale}/sign-up': typeof Char123LocaleChar125SignUpRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/sign-in': typeof Char123LocaleChar125SignInRoute
  '/{-$locale}/sign-up': typeof Char123LocaleChar125SignUpRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/dashboard': typeof Char123LocaleChar125DashboardRoute
  '/{-$locale}/sign-in': typeof Char123LocaleChar125SignInRoute
  '/{-$locale}/sign-up': typeof Char123LocaleChar125SignUpRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}/dashboard'
    | '/{-$locale}/sign-in'
    | '/{-$locale}/sign-up'
    | '/{-$locale}/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/dashboard'
    | '/{-$locale}/sign-in'
    | '/{-$locale}/sign-up'
    | '/{-$locale}'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/sign-in'
    | '/{-$locale}/sign-up'
    | '/{-$locale}/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125DashboardRoute: typeof Char123LocaleChar125DashboardRoute
  Char123LocaleChar125SignInRoute: typeof Char123LocaleChar125SignInRoute
  Char123LocaleChar125SignUpRoute: typeof Char123LocaleChar125SignUpRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/dashboard': {
      id: '/{-$locale}/dashboard'
      path: '/{-$locale}/dashboard'
      fullPath: '/{-$locale}/dashboard'
      preLoaderRoute: typeof Char123LocaleChar125DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/sign-in': {
      id: '/{-$locale}/sign-in'
      path: '/{-$locale}/sign-in'
      fullPath: '/{-$locale}/sign-in'
      preLoaderRoute: typeof Char123LocaleChar125SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/sign-up': {
      id: '/{-$locale}/sign-up'
      path: '/{-$locale}/sign-up'
      fullPath: '/{-$locale}/sign-up'
      preLoaderRoute: typeof Char123LocaleChar125SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125DashboardRoute: Char123LocaleChar125DashboardRoute,
  Char123LocaleChar125SignInRoute: Char123LocaleChar125SignInRoute,
  Char123LocaleChar125SignUpRoute: Char123LocaleChar125SignUpRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
