// <auto-generated />
using System;
using ForgeKit.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForgeKit.Api.Migrations.Sqlite.Migrations.App
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708031112_initial_sqlite")]
    partial class initial_sqlite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.4");

            modelBuilder.Entity("ForgeKit.Api.Entities.Analytics.DailyActivitySnapshot", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ActiveMembers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activeMembers");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedAt");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedBy");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isDeleted");

                    b.Property<DateTime>("SnapshotDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshotDate");

                    b.Property<int>("TodosCompleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("todosCompleted");

                    b.Property<int>("TodosCreated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("todosCreated");

                    b.Property<int>("TodosDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("todosDeleted");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedBy");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspaceId");

                    b.HasKey("Id")
                        .HasName("pkDailyActivitySnapshot");

                    b.HasIndex("SnapshotDate")
                        .HasDatabaseName("ixDailyActivitySnapshotSnapshotDate");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ixDailyActivitySnapshotWorkspaceId");

                    b.HasIndex("SnapshotDate", "WorkspaceId")
                        .HasDatabaseName("ixDailyActivitySnapshotSnapshotDateWorkspaceId");

                    b.HasIndex("SnapshotDate", "WorkspaceId", "IsDeleted")
                        .HasDatabaseName("ixDailyActivitySnapshotSnapshotDateWorkspaceIdIsDeleted");

                    b.ToTable("dailyActivitySnapshot");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Analytics.WorkspaceAnalytics", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("ActiveMembers")
                        .HasColumnType("INTEGER")
                        .HasColumnName("activeMembers");

                    b.Property<decimal?>("AverageCompletionDays")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("averageCompletionDays");

                    b.Property<int>("CancelledTodos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cancelledTodos");

                    b.Property<int>("CompletedTodos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("completedTodos");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedAt");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedBy");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isDeleted");

                    b.Property<string>("MetricsJson")
                        .HasColumnType("text")
                        .HasColumnName("metricsJson");

                    b.Property<int>("OverdueTodos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("overdueTodos");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT")
                        .HasColumnName("periodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT")
                        .HasColumnName("periodStart");

                    b.Property<int>("TotalTodos")
                        .HasColumnType("INTEGER")
                        .HasColumnName("totalTodos");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedBy");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspaceId");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspaceName");

                    b.HasKey("Id")
                        .HasName("pkWorkspaceAnalytics");

                    b.HasIndex("PeriodStart", "PeriodEnd")
                        .HasDatabaseName("ixWorkspaceAnalyticsPeriodStartPeriodEnd");

                    b.HasIndex("WorkspaceId", "PeriodStart")
                        .HasDatabaseName("ixWorkspaceAnalyticsWorkspaceIdPeriodStart");

                    b.HasIndex("PeriodStart", "WorkspaceId", "IsDeleted")
                        .HasDatabaseName("ixWorkspaceAnalyticsPeriodStartWorkspaceIdIsDeleted");

                    b.ToTable("workspaceAnalytics");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Configuration.Category", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("categoryCode");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("categoryName");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedAt");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("displayOrder");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isDeleted");

                    b.Property<string>("ParentCategoryId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("parentCategoryId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedBy");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspaceId");

                    b.HasKey("Id")
                        .HasName("pkCategory");

                    b.HasIndex("CategoryCode")
                        .IsUnique()
                        .HasDatabaseName("ixCategoryCategoryCode");

                    b.HasIndex("ParentCategoryId")
                        .HasDatabaseName("ixCategoryParentCategoryId");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ixCategoryWorkspaceId");

                    b.HasIndex("WorkspaceId", "IsDeleted")
                        .HasDatabaseName("ixCategoryWorkspaceIdIsDeleted");

                    b.ToTable("category");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Configuration.CategoryLabel", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("categoryId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedAt");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedBy");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isDeleted");

                    b.Property<string>("LabelId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("labelId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedBy");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pkCategoryLabel");

                    b.HasIndex("LabelId")
                        .HasDatabaseName("ixCategoryLabelLabelId");

                    b.HasIndex("CategoryId", "LabelId")
                        .HasDatabaseName("ixCategoryLabelCategoryIdLabelId");

                    b.ToTable("categoryLabel");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Configuration.Label", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedAt");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedBy");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isDeleted");

                    b.Property<string>("LabelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("labelCode");

                    b.Property<string>("LabelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("labelName");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedBy");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspaceId");

                    b.HasKey("Id")
                        .HasName("pkLabel");

                    b.HasIndex("LabelCode")
                        .IsUnique()
                        .HasDatabaseName("ixLabelLabelCode");

                    b.HasIndex("WorkspaceId")
                        .HasDatabaseName("ixLabelWorkspaceId");

                    b.ToTable("label");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Core.Member", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedAt");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedBy");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isDeleted");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("joinedAt");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedBy");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("userId");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspaceId");

                    b.HasKey("Id")
                        .HasName("pkMember");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ixMemberUserId");

                    b.HasIndex("WorkspaceId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ixMemberWorkspaceIdUserId");

                    b.ToTable("member");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Core.Workspace", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedAt");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isActive");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isDeleted");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ownerId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedBy");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("WorkspaceCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspaceCode");

                    b.Property<string>("WorkspaceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspaceName");

                    b.HasKey("Id")
                        .HasName("pkWorkspace");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ixWorkspaceOwnerId");

                    b.HasIndex("WorkspaceCode")
                        .IsUnique()
                        .HasDatabaseName("ixWorkspaceWorkspaceCode");

                    b.ToTable("workspace");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Todos.TodoItem", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToMemberId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("assignedToMemberId");

                    b.Property<string>("CategoryId")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("categoryId");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completedAt");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdBy");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("currentStatus");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedAt");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedBy");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("dueDate");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isDeleted");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text")
                        .HasColumnName("metadataJson");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedBy");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspaceId");

                    b.HasKey("Id")
                        .HasName("pkTodoItem");

                    b.HasIndex("AssignedToMemberId")
                        .HasDatabaseName("ixTodoItemAssignedToMemberId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ixTodoItemCategoryId");

                    b.HasIndex("DueDate")
                        .HasDatabaseName("ixTodoItemDueDate");

                    b.HasIndex("WorkspaceId", "CurrentStatus", "IsDeleted")
                        .HasDatabaseName("ixTodoItemWorkspaceIdCurrentStatusIsDeleted");

                    b.ToTable("todoItem");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Todos.TodoStatusHistory", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("changedBy");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("createdBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedAt");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("deletedBy");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("isDeleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.Property<string>("TodoItemId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("todoItemId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("updatedBy");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pkTodoStatusHistory");

                    b.HasIndex("TodoItemId", "Timestamp")
                        .HasDatabaseName("ixTodoStatusHistoryTodoItemIdTimestamp");

                    b.ToTable("todoStatusHistory");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Analytics.DailyActivitySnapshot", b =>
                {
                    b.HasOne("ForgeKit.Api.Entities.Core.Workspace", "Workspace")
                        .WithMany()
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkDailyActivitySnapshotWorkspacesWorkspaceId");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Analytics.WorkspaceAnalytics", b =>
                {
                    b.HasOne("ForgeKit.Api.Entities.Core.Workspace", "Workspace")
                        .WithMany("Analytics")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkWorkspaceAnalyticsWorkspacesWorkspaceId");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Configuration.Category", b =>
                {
                    b.HasOne("ForgeKit.Api.Entities.Configuration.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fkCategoryCategoryParentCategoryId");

                    b.HasOne("ForgeKit.Api.Entities.Core.Workspace", "Workspace")
                        .WithMany("Categories")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fkCategoryWorkspacesWorkspaceId");

                    b.Navigation("ParentCategory");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Configuration.CategoryLabel", b =>
                {
                    b.HasOne("ForgeKit.Api.Entities.Configuration.Category", "Category")
                        .WithMany("CategoryLabels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkCategoryLabelCategoryCategoryId");

                    b.HasOne("ForgeKit.Api.Entities.Configuration.Label", "Label")
                        .WithMany("CategoryLabels")
                        .HasForeignKey("LabelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkCategoryLabelLabelsLabelId");

                    b.Navigation("Category");

                    b.Navigation("Label");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Configuration.Label", b =>
                {
                    b.HasOne("ForgeKit.Api.Entities.Core.Workspace", "Workspace")
                        .WithMany("Labels")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkLabelWorkspacesWorkspaceId");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Core.Member", b =>
                {
                    b.HasOne("ForgeKit.Api.Entities.Core.Workspace", "Workspace")
                        .WithMany("Members")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkMemberWorkspacesWorkspaceId");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Todos.TodoItem", b =>
                {
                    b.HasOne("ForgeKit.Api.Entities.Core.Member", "AssignedTo")
                        .WithMany("AssignedTodoItems")
                        .HasForeignKey("AssignedToMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fkTodoItemMemberAssignedToMemberId");

                    b.HasOne("ForgeKit.Api.Entities.Configuration.Category", "Category")
                        .WithMany("TodoItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fkTodoItemCategoryCategoryId");

                    b.HasOne("ForgeKit.Api.Entities.Core.Workspace", "Workspace")
                        .WithMany("TodoItems")
                        .HasForeignKey("WorkspaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fkTodoItemWorkspaceWorkspaceId");

                    b.Navigation("AssignedTo");

                    b.Navigation("Category");

                    b.Navigation("Workspace");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Todos.TodoStatusHistory", b =>
                {
                    b.HasOne("ForgeKit.Api.Entities.Todos.TodoItem", "TodoItem")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TodoItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fkTodoStatusHistoryTodoItemTodoItemId");

                    b.Navigation("TodoItem");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Configuration.Category", b =>
                {
                    b.Navigation("CategoryLabels");

                    b.Navigation("ChildCategories");

                    b.Navigation("TodoItems");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Configuration.Label", b =>
                {
                    b.Navigation("CategoryLabels");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Core.Member", b =>
                {
                    b.Navigation("AssignedTodoItems");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Core.Workspace", b =>
                {
                    b.Navigation("Analytics");

                    b.Navigation("Categories");

                    b.Navigation("Labels");

                    b.Navigation("Members");

                    b.Navigation("TodoItems");
                });

            modelBuilder.Entity("ForgeKit.Api.Entities.Todos.TodoItem", b =>
                {
                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
